name: 'CompareCC'
description: 'Builds a link for comparing versions and adds it as comment to the PR'
inputs:
  before:
    description: "Base sha"
    required: true
  after:
    description: "Head sha"
    required: true
  filename:
    description: "Yaml to be loaded"
    required: true
  pr_number:
    description: "PR number"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Adding Filters
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          production: '${{ inputs.filename }}-prod.yml'
          training: '${{ inputs.filename }}-trg.yml'
          stage: '${{ inputs.filename }}-stg.yml'
          experimental: '${{ inputs.filename }}-exp.yml'
          validation: '${{ inputs.filename }}-val.yml'
    - run: |
        ls
        git clone https://github.com/MyMedsAndMe/compare_cc_action
        ruby compare_cc_action/link_getter.rb ${{inputs.before}} ${{inputs.after}} ${{inputs.filename}} ${{inputs.pr_number}} ${{steps.filter.outputs.production}} ${{steps.filter.outputs.validation}} ${{steps.filter.outputs.experimental}} ${{steps.filter.outputs.stage}} ${{steps.filter.outputs.training}}
      shell: bash